# {% set posix = 'm2-' if win else '' %}
# {% set native = 'm2w64-' if win else '' %}

package:
  name: sls_detector_gui
  version: "developer"


source:
   git_rev: developer
   git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git
   patches:
    - 00-linking-of-SlsDetector.patch

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - cmake
    # - qwt 6.1.2
    - libpng 
    - pyzmq
    - zlib
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    # - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # - {{ cdt('libxau-devel') }}          # [linux]
    # - {{ cdt('libdrm-devel') }}          # [linux]
    # - {{ cdt('libpng-devel') }}          # [linux]
    # - {{ cdt('libxcomposite-devel') }}   # [linux]
    # - {{ cdt('libxcursor-devel') }}      # [linux]
    # - {{ cdt('libxi-devel') }}           # [linux]
    # - {{ cdt('libxrandr-devel') }}       # [linux]
    # - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    # - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - sls_detector_lib developer
  host:
    - zlib
    - libxcb
    - libpng
    - xorg-libsm
    - xorg-libice
    - sls_detector_lib
    - qwt 6.*
    - qt 4.*

  run:
    - qwt 6.*
    - qt 4.*
    - libpng
    - libstdcxx-ng
    - libgcc-ng
    # - pyzmq
    # - qwt 6.*
    # - qt 4.* 
    - sls_detector_lib developer

about:
  home: no
  license: GPL2
