package:
  name: sls_detector_gui
  version: 3.1.2


source:
   git_rev: 3.1.2
   git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git
   patches:
    - 00-linking-of-SlsDetector.patch
#    - 01-lineFocus.patch

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - cmake
    - gcc 
    - libstdcxx-ng
    - libgcc-ng
    - qwt 6.*
    - qt 4.8.7
    - libpng >=1.6.32,<1.6.35
    - pyzmq
    - sls_detector_lib 3.1.2


  run:
    - qwt 6.*
    - qt 4.8.7
    - libstdcxx-ng
    - libgcc-ng
    - libpng >=1.6.32,<1.6.35
    - pyzmq
    - sls_detector_lib 3.1.2

about:
  home: no
  license: GPL2
