package:
  name: sls_detector_gui
  version: "compiler"


source:
   git_rev: developer
   git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git
   patches:
    - 00-linking-of-SlsDetector.patch
#    - 01-lineFocus.patch

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{compiler('c')}}
    - cmake
    - libstdcxx-ng
    - libgcc-ng
    - qwt 6.*
    - qt 4.8.*
    - libpng >=1.6.32,<1.6.35
    - pyzmq
    - sls_detector_lib compiler


  run:
    - qwt 6.*
    - qt 4.8.*
    - libstdcxx-ng
    - libgcc-ng
    - libpng >=1.6.32,<1.6.35
    - pyzmq
    - sls_detector_lib compiler

about:
  home: no
  license: GPL2
