package:
  name: sls_detector_gui
  version: "compiler"


source:
   git_rev: developer
   git_url: https://github.com/slsdetectorgroup/slsDetectorPackage.git
   patches:
    - linkpatch
#    - 00-linking-of-SlsDetector.patch
#    - 01-lineFocus.patch

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{compiler('c')}}
    - {{compiler('cxx')}}
    - cmake
    - libstdcxx-ng
    - libgcc-ng
    - qwt 6.*
    - qt 4.8.*
    - libpng >=1.6.32,<1.6.35
    - pyzmq
    - sls_detector_lib compiler
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libSM') }}            # [linux]
    - {{ cdt('libICE') }}            # [linux]
  host:
    - pyzmq
    - libpng>=1.6.32
    - qt 4.8.*
    - qwt 6.*

  run:
    - qwt 6.*
    - qt 4.8.*
    - libstdcxx-ng
    - libgcc-ng
    - libpng >=1.6.32,<1.6.35
    - pyzmq
    - sls_detector_lib compiler

about:
  home: no
  license: GPL2
